// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "nmb-20181206083858--hostingbucket-nmbenv",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://nmb-20181206083858--hostingbucket-nmbenv.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:004e19f1-6a27-4c87-a910-96703d17396b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NXjIE1ry2",
    "aws_user_pools_web_client_id": "i22jsnce35g6mbq518upe9knr",
    "oauth": {},
    "aws_user_files_s3_bucket": "nmb-content-nmbenv",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
